env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - react-app
  
globals:

  process: true
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - "@typescript-eslint"
rules:
  {
    quotes: [error, single],
    semi: [error],
    object-curly-spacing: [error, always],
    indent: [2, "tab"]
  }
overrides: [
  {
    files: ["**/*.ts?(x)"]
  }
]
    
